---
title: "R Notebook"
author: "Manazir"
---

###5.1

```{r, echo=F, eval=F}

library("here")
library("tidyverse")
library("lubridate")
```


```{r, eval=F}
films <- c(
  "A New Hope", "The Empire Strikes Back", "Return of the Jedi",
  "The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
  "The Force Awakens", "The Last Jedi", "The Rise of Skywalker"
)
```

```{r}
survey_results_2 <-
  c("Rogue One", "A New Hope", "The Force Awakens", "A New Hope", "The Empire Strikes Back")
```
a.

```{r, echo=F, eval=F}
factor(survey_results_2, levels = films)
```
b.

```{r, echo=F, eval=F}
z <- factor(survey_results_2, levels= c(films, "Rogue One"))
z
```

c. 

```{r, echo=F, eval=F}
z <- factor(survey_results_2, levels = c(films[4:6], "Rogue One", films [c(1:3, 7:9)]))

# z <- factor(survey_results_2, levels = c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith", "Rogue One", "A New Hope", "The Empire Strikes Back", "Return of the Jedi", "The Force Awakens", "The Last Jedi", "The Rise of Skywalker"))
# z

```

d.

```{r, eval=F, echo=F}
# u <- ordered(z, levels = levels(z))
# u[1]
# u[2]
# u[1] < u[2]



```

###5.2


```{r}
months <- c("Feb", "March", "DEC", "Nov", "Mar", "Jul", "Jan", "Jul", "jul")
```

```{r, eval=F, echo=F}
# z_abb <- factor(months, levels = unique (c(month.name, months)))
# 
# z_abb <- factor(months, levels = unique(c(month.name, months)))

```
b.

```{r, eval=F, echo=T}
# levels(z_abb) <- c(month.abb, "Mar", "Dec", "Jul")

```

### 5.3
```{r, echo= F, eval = F}
# time_birth <- as_datetime( "1999-02-20 11:20:00", tz ="Asia/Bangladesh")
# 
# diff <- as.duration(now() - time_birth)
# paste(diff, "have passed since my birth")

```

###5.5

```{r, echo=F, eval=F}
starwars %>%
  # filter(str_detect(name, "-"))

# mutate(name = str_sub(name, start = 1L, end = 3L))
  
  # mutate(name = str_replace_all(name, pattern = "2", replacement = "Two"))
  
  

```

###5.6

```{r, echo=F, eval=F}
df <- tibble(
  a = c(T, F),
  b = c(1L, 2L),
  c = c(pi , sqrt(2)),
  d = c( "x", "y"),
  e = list("a", "b"),
  f= list(x= "a", y = "b"),
  g= factor (d) ,
  h = ordered(d),
  i = c(today(), today() -1), 
  j= c(now(), now() - 1),
  k = c(today() - (i - 1)),
  l = as.duration (k)
  
)
 glimpse (df)
 
```


